// <auto-generated />
using ClassCrawler.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassCrawler.Data.Migrations.ClassMariaDb
{
    [DbContext(typeof(ClassMariaDbContext))]
    [Migration("20210504095413_changePriceType2String")]
    partial class changePriceType2String
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClassCrawler.Data.Models.ClassInfo", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ClassDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClassImg")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClassName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClassPrice")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClassStatus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClassTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ClassId");

                    b.ToTable("ClassInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
